#!/usr/bin/env bash

# First, it uses the Spectrum API to convert audio to text.
NQ_AUDIO_DOC_ID="q01vDxALebMNfDBKo33o"

curl -X POST https://api-power-skills.neuroquest.ai/api/v1/predict/create \
  -H "Content-Type: application/json" \
  -H "token: ${NQ_TOKEN}" \
  -d "{\"name\": \"Gabriela Ehlert\", \"essay\": \"${NQ_AUDIO_DOC_ID}\"}" | jq .

exit 0
