#!/usr/bin/env bash

curl -X POST https://api-persona-predict.neuroquest.ai/api/v2/auth/login \
  -H "Content-Type: application/json" \
  -d "{\"email\": \"${NQ_EMAIL}\", \"password\": \"${NQ_PASSWORD}\"}" | jq .

exit 0
