#!/usr/bin/env bash

curl -X POST https://api-persona-predict.neuroquest.ai/api/v2/predict/create \
  -H "Content-Type: application/json" \
  -H "token: ${NQ_TOKEN}" \
  -d "{\"name\": \"John Green\", \"essay\": \"${NQ_ESSAY}\", \"task\": \"false\"}" | jq .

exit 0
