#!/usr/bin/env bash

AUDIO_FILENAME="./audio/John-F-Kennedy-Speech-1962-09-12-CUT.mp3"
AUDIO_LANG="en"

resp=$(curl -X POST https://api-spectrum.neuroquest.ai/api/v1/audio/to-text \
  -H "Content-Type: multipart/form-data" \
  -F "audio_file=@${AUDIO_FILENAME}" \
  -F "audio_lang=${AUDIO_LANG}" \
  -H "token: ${NQ_TOKEN}" | jq .)

echo "${resp}"

exit 0
